### Tarefa 1 do Módulo 9 do Curso de Ciência de Dados da EBAC

# Visão Geral

O SINASC é o Sistema de Informações sobre Nascidos Vivos. Ele foi implantado oficialmente a partir de 1990 com o objetivo de coletar dados sobre os nascimentos ocorridos em todo o território nacional e fornecer informações sobre natalidade para todos os níveis do Sistema de Saúde.

### A importância dos dados do SINASC para a gestão em Saúde

O Ministério da Saúde, através da CGIAE/DASNT/SVS, incentiva os gestores municipais e estaduais a fazerem uso do potencial de dados contido no SINASC, para a formulação de indicadores epidemiológicos como instrumentos estratégicos de suporte ao planejamento das ações, atividades e programas voltados à gestão em saúde.

O nascimento é um dos eventos vitais e seu monitoramento pode contribuir para o conhecimento da situação de saúde de uma população e para a avaliação de políticas e ações de vigilância e atenção à saúde na área da saúde materno-infantil.

### Sobre este projeto

Usando os conhecimentos adquiridos até aqui, iremos realizar uma análise exploratória dos dados de natalidade do estado de Rondônia no ano de 2019 afim de identificar possíveis problemas de saúde pública e entender como eles afetam a população.

### Como são obtidos e processados os dados do SINASC

As DN são preenchidas pelos profissionais de saúde, ou parteiras tradicionais responsáveis pela assistência ao parto ou ao recém-nascido (reconhecidas e vinculadas a unidades de saúde), no caso dos partos hospitalares ou domiciliares com assistência e recolhidas, regularmente, pelas Secretarias Municipais de Saúde.

Nas Secretarias Municipais de Saúde, as DN são digitadas, processadas, criticadas e consolidadas no SINASC local. Em seguida, os dados informados pelos municípios sobre os nascimentos no nível local são transferidos à base de dados do nível estadual que os agrega e os envia ao nível federal. Tais transferências são realizadas via WEB (internet) e ocorrem, simultaneamente, nos três níveis de gestão. No nível federal, a SVS/MS - gestora do SINASC - conta, na sua estrutura funcional, com a Coordenação-Geral de Informações e Análises Epidemiológicas (CGIAE). Subordinada ao Departamento de Análise em Saúde e Vigilância das Doenças Não Transmissíveis (DASNT), a CGIAE trata da análise, avaliação e distribuição das informações sobre o SINASC, agregando-as por Unidade da Federação, e elaborando relatórios analíticos, painéis de indicadores e outros instrumentos estatísticos de informações sobre natalidade que são disseminados para todo o país.

*Fonte*: https://www.gov.br/saude/pt-br/composicao/svsa/vigilancia-de-doencas-cronicas-nao-transmissiveis/sistemas-de-informacao-em-saude

## Dicionário de Variáveis

| Variável        | Significado                                               |
|-----------------|-----------------------------------------------------------|
| ORIGEM          | Banco de dados de Origem 1- Oracle, 2- FTP, 3- SEAD                                              |
| CODESTAB        | Código de estabelecimento                                 |
| CODMUNNASC      | Município de ocorrência do nascimento                     |
| LOCNASC         | Local de ocorrência do nascimento                         |
| IDADEMAE        | Idade da mãe em anos                                      |
| ESTCIVMAE       | Estado civil da mãe                                       |
| ESCMAE          | Escolaridade da mãe                                       |
| CODOCUPMAE      | Ocupação da mãe                                           |
| QTDFILVIVO      | Número de filhos vivos                                    |
| QTDFILMORT      | Número de filhos mortos                                   |
| CODMUNRES       | Município de residência da mãe                            |
| GESTACAO        | Semanas de gestação                                       |
| GRAVIDEZ        | Tipo de gravidez                                          |
| PARTO           | Tipo de parto                                             |
| CONSULTAS       | Número de consultas de pré-natal                          |
| DTNASC          | Data do nascimento                                        |
| HORANASC        | Horário de nascimento                                      |
| SEXO            | Sexo do recém-nascido                                     |
| APGAR1          | Apgar no primeiro minuto                                   |
| APGAR5          | Apgar no quinto minuto                                    |
| RACACOR         | Raça/Cor                                                  |
| PESO            | Peso ao nascer                                            |
| IDANOMAL        | Anomalia congênita                                        |
| DTCADASTRO      | Data do cadastro da Declaração de Nascido Vivo (DN)       |
| CODANOMAL       | Código de malformação congênita ou anomalia cromossômica  |
| NUMEROLOTE      | Número do lote                                            |
| VERSAOSIST      | Versão do sistema                                         |
| DTRECEBIM       | Data de recebimento no nível central                      |
| DIFDATA         | Diferença entre a data de óbito e a data do recebimento original da DO  |
| DTRECORIGA      | Data do primeiro recebimento do lote                       |
| NATURALMAE      | Código do país de nascimento da mãe                        |
| CODMUNNATU      | Código do município de naturalidade da mãe                |
| CODUFNATU       | Código da UF de naturalidade da mãe                       |
| ESCMAE2010      | Escolaridade da mãe em 2010                               |
| SERIESCMAE      | Série escolar da mãe                                      |
| DTNASCMAE       | Data de nascimento da mãe                                 |
| RACACORMAE      | Raça/cor da mãe                                           |
| QTDGESTANT      | Número de gestações anteriores                            |
| QTDPARTNOR      | Número de partos vaginais                                 |
| QTDPARTCES      | Número de partos cesáreos                                 |
| IDADEPAI        | Idade do pai                                              |
| DTULTMENST      | Data da última menstruação (DUM)                          |
| SEMAGESTAC      | Número de semanas de gestação                             |
| TPMETESTIM      | Método utilizado                                          |
| CONSPRENAT      | Número de consultas pré-natal                              |
| MESPRENAT       | Mês de gestação em que iniciou o pré-natal                 |
| TPAPRESENT      | Tipo de apresentação do recém-nascido                      |
| STTRABPART      | Trabalho de parto induzido                                |
| STCESPARTO      | Cesárea ocorreu antes do trabalho de parto iniciar        |
| TPNASCASSI      | Nascimento foi assistido por                               |
| TPFUNCRESP      | Tipo de função do responsável pelo preenchimento           |
| TPDOCRESP       | Tipo do documento do responsável                           |
| DTDECLARAC      | Data da declaração                                        |
| ESCMAEAGR1      | Escolaridade 2010 agregada                                 |
| STDNEPIDEM      | Status de DO Epidemiológica                                |
| STDNNOVA        | Status de DO Nova                                          |
| CODPAISRES      | Código do país de residência                               |
| TPROBSON        | Código do Grupo de Robson                                  |
| PARIDADE        | Define se é a primeira gravidez ou se teve mais de uma. 1 – Multípara; 0- Nulípara                                           |
| KOTELCHUCK      | índice de Kotelchuck - Avaliação da assistência pré-nata                                             |
| CONTADOR        | Número identificador do registro                                              |
| munResStatus    | Sem descrição                                             |
| munResTipo      | Sem descrição                                             |
| munResNome      | Nome do Munícipio de Residência                                           |
| munResUf        | Sem descrição                                             |
| munResLat       | Latitude do Municipio de Residencia                       |
| munResLon       | Longitude do Municipio de Residencia                      |
| munResAlt       | Altitude do Municipio de Residencia                       |
| munResArea      | Área do Municipio de Residencia                           |

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [3]:
df = pd.read_csv('SINASC_RO_2019.csv')
df.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27028 entries, 0 to 27027
Data columns (total 69 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ORIGEM        27028 non-null  int64
 1   CODESTAB      26913 non-null  float64
 2   CODMUNNASC    27028 non-null  int64
 3   LOCNASC       27028 non-null  int64
 4   IDADEMAE      27028 non-null  int64
 5   ESTCIVMAE     26711 non-null  float64
 6   ESCMAE        26716 non-null  object
 7   CODOCUPMAE    24121 non-null  float64
 8   QTDFILVIVO    25455 non-null  float64
 9   QTDFILMORT    24930 non-null  float64
 10  CODMUNRES     27028 non-null  int64
 11  GESTACAO      25796 non-null  object
 12  GRAVIDEZ      26949 non-null  object
 13  PARTO         26979 non-null  object
 14  CONSULTAS     27028 non-null  int64
 15  DTNASC        27028 non-null  object
 16  HORANASC      27007 non-null  float64
 17  SEXO          27024 non-null  object
 18  APGAR1        26932 non-null  float64
 19  APGAR5        26925 non-null  float64
 20  RACACOR       26381 non-null  object
 21  PESO          27028 non-null  int64
 22  IDANOMAL      26437 non-null  float64
 23  DTCADASTRO    27028 non-null  object
 24  CODANOMAL     214 non-null    object
 25  NUMEROLOTE    27028 non-null  int64
 26  VERSAOSIST    27028 non-null  object
 27  DTRECEBIM     27028 non-null  object
 28  DIFDATA       27028 non-null  int64
 29  DTRECORIGA    0 non-null      float64
 30  NATURALMAE    26730 non-null  float64
 31  CODMUNNATU    26730 non-null  float64
 32  CODUFNATU     26730 non-null  float64
 33  ESCMAE2010    26779 non-null  float64
 34  SERIESCMAE    14318 non-null  float64
 35  DTNASCMAE     26988 non-null  float64
 36  RACACORMAE    26367 non-null  float64
 37  QTDGESTANT    25816 non-null  float64
 38  QTDPARTNOR    25149 non-null  float64
 39  QTDPARTCES    25237 non-null  float64
 40  IDADEPAI      7607 non-null   float64
 41  DTULTMENST    16956 non-null  float64
 42  SEMAGESTAC    25790 non-null  float64
 43  TPMETESTIM    25790 non-null  float64
 44  CONSPRENAT    26098 non-null  float64
 45  MESPRENAT     24161 non-null  float64
 46  TPAPRESENT    26763 non-null  float64
 47  STTRABPART    26081 non-null  float64
 48  STCESPARTO    26281 non-null  float64
 49  TPNASCASSI    26967 non-null  float64
 50  TPFUNCRESP    26961 non-null  float64
 51  TPDOCRESP     27014 non-null  float64
 52  DTDECLARAC    26976 non-null  float64
 53  ESCMAEAGR1    26779 non-null  float64
 54  STDNEPIDEM    27028 non-null  int64
 55  STDNNOVA      27028 non-null  int64
 56  CODPAISRES    27028 non-null  int64
 57  TPROBSON      27028 non-null  int64
 58  PARIDADE      27028 non-null  int64
 59  KOTELCHUCK    27028 non-null  int64
 60  CONTADOR      27028 non-null  int64
 61  munResStatus  27028 non-null  object
 62  munResTipo    27028 non-null  object
 63  munResNome    27028 non-null  object
 64  munResUf      27028 non-null  object
 65  munResLat     27027 non-null  float64
 66  munResLon     27027 non-null  float64
 67  munResAlt     27027 non-null  float64
 68  munResArea    27027 non-null  float64
dtypes: float64(38), int64(16), object(15)
memory usage: 14.2+ MB

In [5]:
def stats_dados_faltantes(df: pd.DataFrame) -> None: #definindo função para verificarmos estatisticas dos dados faltantes

  stats_dados_faltantes = [] #criando uma lista com informações dos dados faltantes
  for col in df.columns: #chama cada coluna do dataframe para analise
    if df[col].isna().any(): #se a coluna em analise possuir dados vazios (retorno = True), executa os códigos abaixo
      qtd, _ = df[df[col].isna()].shape #define a variavel qtd que é igual a quantidade de dados vazios dentro da coluna
      total, _ = df.shape #define a variavel total que é igual a quantidade de linhas dos dataframe
      dict_dados_faltantes = {col: {'quantidade': qtd, "porcentagem": round(100 * qtd/total, 2)}} #cria dicionarios da coluna com quantidade de dados faltantes e sua porcentagem salvas
      stats_dados_faltantes.append(dict_dados_faltantes) #adiciona os dicionarios criados na lista criada inicialmente

  for stat in stats_dados_faltantes:
    print(stat)

Acima utilizamos uma função para analisar cada coluna e se esta coluna possuir dados faltantes, ela salva o nome da coluna, a quantidade de dados faltantes e a porcentagem destes dados em uma lista.

In [6]:
stats_dados_faltantes(df=df)

{'CODESTAB': {'quantidade': 115, 'porcentagem': 0.43}}
{'ESTCIVMAE': {'quantidade': 317, 'porcentagem': 1.17}}
{'ESCMAE': {'quantidade': 312, 'porcentagem': 1.15}}
{'CODOCUPMAE': {'quantidade': 2907, 'porcentagem': 10.76}}
{'QTDFILVIVO': {'quantidade': 1573, 'porcentagem': 5.82}}
{'QTDFILMORT': {'quantidade': 2098, 'porcentagem': 7.76}}
{'GESTACAO': {'quantidade': 1232, 'porcentagem': 4.56}}
{'GRAVIDEZ': {'quantidade': 79, 'porcentagem': 0.29}}
{'PARTO': {'quantidade': 49, 'porcentagem': 0.18}}
{'HORANASC': {'quantidade': 21, 'porcentagem': 0.08}}
{'SEXO': {'quantidade': 4, 'porcentagem': 0.01}}
{'APGAR1': {'quantidade': 96, 'porcentagem': 0.36}}
{'APGAR5': {'quantidade': 103, 'porcentagem': 0.38}}
{'RACACOR': {'quantidade': 647, 'porcentagem': 2.39}}
{'IDANOMAL': {'quantidade': 591, 'porcentagem': 2.19}}
{'CODANOMAL': {'quantidade': 26814, 'porcentagem': 99.21}}
{'DTRECORIGA': {'quantidade': 27028, 'porcentagem': 100.0}}
{'NATURALMAE': {'quantidade': 298, 'porcentagem': 1.1}}
{'CODMUNNATU': {'quantidade': 298, 'porcentagem': 1.1}}
{'CODUFNATU': {'quantidade': 298, 'porcentagem': 1.1}}
{'ESCMAE2010': {'quantidade': 249, 'porcentagem': 0.92}}
{'SERIESCMAE': {'quantidade': 12710, 'porcentagem': 47.03}}
{'DTNASCMAE': {'quantidade': 40, 'porcentagem': 0.15}}
{'RACACORMAE': {'quantidade': 661, 'porcentagem': 2.45}}
{'QTDGESTANT': {'quantidade': 1212, 'porcentagem': 4.48}}
{'QTDPARTNOR': {'quantidade': 1879, 'porcentagem': 6.95}}
{'QTDPARTCES': {'quantidade': 1791, 'porcentagem': 6.63}}
{'IDADEPAI': {'quantidade': 19421, 'porcentagem': 71.86}}
{'DTULTMENST': {'quantidade': 10072, 'porcentagem': 37.27}}
{'SEMAGESTAC': {'quantidade': 1238, 'porcentagem': 4.58}}
{'TPMETESTIM': {'quantidade': 1238, 'porcentagem': 4.58}}
{'CONSPRENAT': {'quantidade': 930, 'porcentagem': 3.44}}
{'MESPRENAT': {'quantidade': 2867, 'porcentagem': 10.61}}
{'TPAPRESENT': {'quantidade': 265, 'porcentagem': 0.98}}
{'STTRABPART': {'quantidade': 947, 'porcentagem': 3.5}}
{'STCESPARTO': {'quantidade': 747, 'porcentagem': 2.76}}
{'TPNASCASSI': {'quantidade': 61, 'porcentagem': 0.23}}
{'TPFUNCRESP': {'quantidade': 67, 'porcentagem': 0.25}}
{'TPDOCRESP': {'quantidade': 14, 'porcentagem': 0.05}}
{'DTDECLARAC': {'quantidade': 52, 'porcentagem': 0.19}}
{'ESCMAEAGR1': {'quantidade': 249, 'porcentagem': 0.92}}
{'munResLat': {'quantidade': 1, 'porcentagem': 0.0}}
{'munResLon': {'quantidade': 1, 'porcentagem': 0.0}}
{'munResAlt': {'quantidade': 1, 'porcentagem': 0.0}}
{'munResArea': {'quantidade': 1, 'porcentagem': 0.0}}

In [7]:
df.select_dtypes('object').describe().transpose() #verificando os atributos categóricos

              count unique              top   freq
ESCMAE        26716      5      8 a 11 anos  15633
GESTACAO      25796      6  37 a 41 semanas  22589
GRAVIDEZ      26949      3            Única  26452
PARTO         26979      2          Cesáreo  18036
DTNASC        27028    365       2019-04-10    116
SEXO          27024      2        Masculino  13886
RACACOR       26381      5            Parda  19594
DTCADASTRO    27028    321       2019-03-08    265
CODANOMAL       214    114             Q699     17
VERSAOSIST    27028      3           3.2.01  27017
DTRECEBIM     27028    232       2020-01-15    836
munResStatus  27028      2            ATIVO  27027
munResTipo    27028      2            MUNIC  27027
munResNome    27028     53      Porto Velho   8437
munResUf      27028      1         Rondônia  27028

In [8]:
df.select_dtypes('number').describe().transpose() #verificando os atributos númericos

,count,mean,std,min,25%,50%,75%,max
ORIGEM,27028.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
CODESTAB,26913.0,3.267629e+06,1.122677e+06,1.531800e+04,2.496534e+06,2.798484e+06,3.970442e+06,9.659366e+06
CODMUNNASC,27028.0,1.110378e+05,1.810275e+04,1.100010e+05,1.100110e+05,1.100200e+05,1.100200e+05,5.208700e+05
LOCNASC,27028.0,1.011396e+00,1.616792e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.000000e+00
IDADEMAE,27028.0,2.609372e+01,6.387094e+00,1.100000e+01,2.100000e+01,2.600000e+01,3.100000e+01,5.300000e+01
ESTCIVMAE,26711.0,2.545318e+00,1.671248e+00,1.000000e+00,1.000000e+00,2.000000e+00,5.000000e+00,9.000000e+00
CODOCUPMAE,24121.0,7.956040e+05,2.838850e+05,1.020500e+04,5.211250e+05,9.999920e+05,9.999920e+05,9.999940e+05
QTDFILVIVO,25455.0,1.053899e+00,1.170874e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+01
QTDFILMORT,24930.0,2.665062e-01,6.139085e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.800000e+01
CODMUNRES,27028.0,1.100291e+05,3.603647e+01,1.100000e+05,1.100120e+05,1.100200e+05,1.100280e+05,1.101800e+05
CONSULTAS,27028.0,3.576402e+00,7.884923e-01,1.000000e+00,3.000000e+00,4.000000e+00,4.000000e+00,9.000000e+00
HORANASC,27007.0,1.267470e+03,5.749223e+02,0.000000e+00,9.050000e+02,1.230000e+03,1.715000e+03,2.359000e+03
APGAR1,26932.0,8.137457e+00,9.849247e-01,0.000000e+00,8.000000e+00,8.000000e+00,9.000000e+00,1.000000e+01
APGAR5,26925.0,9.179164e+00,7.905744e-01,0.000000e+00,9.000000e+00,9.000000e+00,1.000000e+01,1.000000e+01
PESO,27028.0,3.243191e+03,5.447541e+02,2.580000e+02,2.965000e+03,3.270000e+03,3.575000e+03,5.985000e+03
IDANOMAL,26437.0,2.030034e+00,5.235473e-01,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,9.000000e+00
NUMEROLOTE,27028.0,2.019059e+07,2.412071e+03,2.018001e+07,2.019000e+07,2.019001e+07,2.019001e+07,2.020013e+07
DIFDATA,27028.0,3.216546e+01,2.546116e+01,1.000000e+00,1.800000e+01,2.800000e+01,3.900000e+01,6.520000e+02
DTRECORIGA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NATURALMAE,26730.0,8.149188e+02,9.892395e+00,8.110000e+02,8.110000e+02,8.110000e+02,8.110000e+02,8.530000e+02
CODMUNNATU,26730.0,1.493503e+05,9.919561e+04,1.100000e+05,1.100110e+05,1.100200e+05,1.100370e+05,5.300100e+05
CODUFNATU,26730.0,1.491882e+01,9.892395e+00,1.100000e+01,1.100000e+01,1.100000e+01,1.100000e+01,5.300000e+01
ESCMAE2010,26779.0,3.040442e+00,1.090415e+00,0.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,9.000000e+00
SERIESCMAE,14318.0,4.190250e+00,2.370539e+00,1.000000e+00,3.000000e+00,3.000000e+00,7.000000e+00,8.000000e+00
DTNASCMAE,26988.0,1.581702e+07,8.794548e+06,1.011979e+06,8.081990e+06,1.604199e+07,2.311199e+07,3.112200e+07
RACACORMAE,26367.0,3.333220e+00,1.242658e+00,1.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,5.000000e+00
QTDGESTANT,25816.0,1.275101e+00,1.404597e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,5.200000e+01
QTDPARTNOR,25149.0,5.794266e-01,1.209136e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.100000e+01
QTDPARTCES,25237.0,5.205056e-01,7.463293e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.200000e+01
IDADEPAI,7607.0,3.109241e+01,7.771165e+00,1.500000e+01,2.500000e+01,3.000000e+01,3.600000e+01,8.600000e+01
DTULTMENST,16956.0,1.557824e+07,8.607785e+06,1.012019e+06,8.062018e+06,1.510202e+07,2.307202e+07,3.112202e+07
SEMAGESTAC,25790.0,3.856735e+01,2.016802e+00,1.900000e+01,3.800000e+01,3.900000e+01,4.000000e+01,4.500000e+01
TPMETESTIM,25790.0,6.552307e+00,2.911073e+00,1.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,9.000000e+00
CONSPRENAT,26098.0,8.254924e+00,5.143073e+00,0.000000e+00,6.000000e+00,8.000000e+00,1.000000e+01,9.900000e+01
MESPRENAT,24161.0,8.129423e+00,2.267253e+01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,9.900000e+01
TPAPRESENT,26763.0,1.062437e+00,4.910327e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00
STTRABPART,26081.0,1.985200e+00,6.417327e-01,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,9.000000e+00
STCESPARTO,26281.0,2.296260e+00,1.357001e+00,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,9.000000e+00
TPNASCASSI,26967.0,1.146216e+00,4.253374e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00
TPFUNCRESP,26961.0,2.542265e+00,1.217822e+00,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,5.000000e+00
TPDOCRESP,27014.0,2.992893e+00,1.172600e+00,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
DTDECLARAC,26976.0,1.574860e+07,8.744895e+06,1.012019e+06,8.082019e+06,1.602202e+07,2.309202e+07,3.112202e+07
ESCMAEAGR1,26779.0,7.034654e+00,3.083847e+00,0.000000e+00,5.000000e+00,6.000000e+00,8.000000e+00,1.200000e+01
STDNEPIDEM,27028.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
STDNNOVA,27028.0,9.997780e-01,1.489802e-02,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
CODPAISRES,27028.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
TPROBSON,27028.0,4.328437e+00,2.930690e+00,1.000000e+00,2.000000e+00,4.000000e+00,5.000000e+00,1.100000e+01
PARIDADE,27028.0,6.487716e-01,4.773630e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
KOTELCHUCK,27028.0,4.974952e+00,2.067085e+00,1.000000e+00,4.000000e+00,5.000000e+00,5.000000e+00,9.000000e+00
CONTADOR,27028.0,7.367650e+05,7.430325e+05,1.000000e+00,6.802750e+03,1.364550e+04,1.486846e+06,2.780269e+06
munResLat,27027.0,-1.037799e+01,1.372942e+00,-1.349976e+01,-1.143387e+01,-1.043595e+01,-8.768890e+00,-8.768890e+00
munResLon,27027.0,-6.275499e+01,1.269490e+00,-6.532915e+01,-6.383145e+01,-6.303327e+01,-6.194509e+01,-6.013858e+01
munResAlt,27027.0,1.791120e+02,1.231384e+02,8.500000e+01,8.700000e+01,1.530000e+02,1.910000e+02,5.950000e+02
munResArea,27027.0,1.470280e+04,1.370618e+04,4.599780e+02,3.792998e+03,6.896648e+03,3.409639e+04,3.409639e+04

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [12]:
# Calculando a idade média das mães por município
idade_media_mae = df.groupby('munResNome')['IDADEMAE'].mean()

# Calculando a idade média dos pais por município
idade_media_pai = df.groupby('munResNome')['IDADEPAI'].mean()

In [13]:
idade_media_mae = pd.DataFrame(idade_media_mae)
idade_media_mae

                            IDADEMAE
munResNome
Alta Floresta D'Oeste      25.991826
Alto Alegre dos Parecis    24.844156
Alto Paraíso               24.960177
Alvorada D'Oeste           25.770732
Ariquemes                  25.607866
Buritis                    25.559177
Cabixi                     26.037500
Cacaulândia                25.546667
Cacoal                     26.890102
Campo Novo de Rondônia     24.825301
Candeias do Jamari         25.243323
Castanheiras               27.281250
Cerejeiras                 27.240506
Chupinguaia                25.333333
Colorado do Oeste          27.602804
Corumbiara                 24.716535
Costa Marques              24.412017
Cujubim                    24.482927
Espigão D'Oeste            26.093333
Governador Jorge Teixeira  24.401786
Guajará-Mirim              25.462228
Itapuã do Oeste            26.064220
Jaru                       25.982974
Ji-Paraná                  26.361137
Machadinho D'Oeste         25.480000
Ministro Andreazza         27.904762
Mirante da Serra           26.304878
Monte Negro                25.648241
Município ignorado - RO    24.000000
Nova Brasilândia D'Oeste   26.222222
Nova Mamoré                25.326389
Nova União                 26.894231
Novo Horizonte do Oeste    26.938776
Ouro Preto do Oeste        26.375594
Parecis                    26.454545
Pimenta Bueno              25.199675
Pimenteiras do Oeste       25.075000
Porto Velho                26.312670
Presidente Médici          25.796053
Primavera de Rondônia      27.023256
Rio Crespo                 26.660000
Rolim de Moura             26.600863
Santa Luzia D'Oeste        26.121212
Seringueiras               24.910714
São Felipe D'Oeste         26.481481
São Francisco do Guaporé   25.660066
São Miguel do Guaporé      25.926346
Teixeirópolis              26.031250
Theobroma                  25.536082
Urupá                      26.688235
Vale do Anari              26.096774
Vale do Paraíso            25.679012
Vilhena                    26.433962

In [14]:
idade_media_pai = pd.DataFrame(idade_media_pai)
idade_media_pai

                            IDADEPAI
munResNome
Alta Floresta D'Oeste      29.548701
Alto Alegre dos Parecis    29.179104
Alto Paraíso               28.833333
Alvorada D'Oeste           30.757282
Ariquemes                  32.466667
Buritis                    30.812500
Cabixi                     34.333333
Cacaulândia                36.333333
Cacoal                     30.931854
Campo Novo de Rondônia     30.500000
Candeias do Jamari         29.894737
Castanheiras               30.392857
Cerejeiras                 31.652778
Chupinguaia                29.629630
Colorado do Oeste          34.354839
Corumbiara                 32.470588
Costa Marques              30.613636
Cujubim                    31.400000
Espigão D'Oeste            31.198113
Governador Jorge Teixeira  29.222222
Guajará-Mirim              30.470588
Itapuã do Oeste            42.500000
Jaru                       32.197183
Ji-Paraná                  31.132239
Machadinho D'Oeste         31.326923
Ministro Andreazza         33.849315
Mirante da Serra           32.154762
Monte Negro                34.678571
Município ignorado - RO    22.000000
Nova Brasilândia D'Oeste   30.520833
Nova Mamoré                31.692308
Nova União                 31.371429
Novo Horizonte do Oeste    31.588235
Ouro Preto do Oeste        31.233244
Parecis                    32.473684
Pimenta Bueno              29.745174
Pimenteiras do Oeste       35.600000
Porto Velho                32.352679
Presidente Médici          30.150754
Primavera de Rondônia      31.888889
Rio Crespo                 28.000000
Rolim de Moura             30.360479
Santa Luzia D'Oeste        30.703297
Seringueiras               30.500000
São Felipe D'Oeste         31.395833
São Francisco do Guaporé   31.638889
São Miguel do Guaporé      32.666667
Teixeirópolis              31.500000
Theobroma                  30.083333
Urupá                      31.008929
Vale do Anari              34.000000
Vale do Paraíso            29.976744
Vilhena                    34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [15]:
df.DTNASC

0        2019-02-19
1        2019-02-21
2        2019-02-25
3        2019-03-20
4        2019-03-23
            ...
27023    2019-12-13
27024    2019-10-04
27025    2019-08-02
27026    2019-12-23
27027    2019-12-27
Name: DTNASC, Length: 27028, dtype: object

A coluna _DTNASC_ está no tipo _object_. Vamos converter para _datetime_.

In [16]:
# Convertendo a coluna 'DTNASC' para o formato datetime
df['DTNASC'] = pd.to_datetime(df['DTNASC'], format='%Y-%m-%d', errors='coerce')

In [17]:
df.ESCMAE

0            8 a 11 anos
1            8 a 11 anos
2            8 a 11 anos
3        12 anos ou mais
4            8 a 11 anos
              ...
27023    12 anos ou mais
27024        8 a 11 anos
27025        8 a 11 anos
27026        8 a 11 anos
27027        8 a 11 anos
Name: ESCMAE, Length: 27028, dtype: object

In [18]:
# Contar a frequência de cada valor na coluna 'ESCMAE'
contagem_escmae = df['ESCMAE'].value_counts()

# Calcular a porcentagem dividindo pelo total de registros
porcentagem_escmae = (contagem_escmae / len(df)) * 100

# Exibir os resultados
print("Porcentagem de cada valor na coluna 'ESCMAE':\n", porcentagem_escmae)

Porcentagem de cada valor na coluna 'ESCMAE':
 ESCMAE
8 a 11 anos        57.840018
12 anos ou mais    21.337132
4 a 7 anos         17.611366
1 a 3 anos          1.909131
Nenhuma             0.147995
Name: count, dtype: float64

In [19]:
# Calcular a porcentagem de valores ausentes na coluna 'ESCMAE'
porcentagem_ausentes = (df['ESCMAE'].isna().sum() / len(df)) * 100

# Exibir a porcentagem de valores ausentes
print("Porcentagem de valores ausentes na coluna 'ESCMAE':", porcentagem_ausentes)

Porcentagem de valores ausentes na coluna 'ESCMAE': 1.1543584430960485

In [20]:
# Calculando o peso médio dos bebês por sexo e faixa de escolaridade
peso_medio_por_sexo_escolaridade = df.groupby(['SEXO', 'ESCMAE'])['PESO'].mean().reset_index()

# Exibindo os resultados
print("Peso médio dos bebês por sexo e faixa de escolaridade:\n", peso_medio_por_sexo_escolaridade)

Peso médio dos bebês por sexo e faixa de escolaridade:
         SEXO           ESCMAE         PESO
0   Feminino       1 a 3 anos  3126.363636
1   Feminino  12 anos ou mais  3182.427912
2   Feminino       4 a 7 anos  3158.036123
3   Feminino      8 a 11 anos  3193.250588
4   Feminino          Nenhuma  2972.333333
5  Masculino       1 a 3 anos  3191.354386
6  Masculino  12 anos ou mais  3309.658421
7  Masculino       4 a 7 anos  3288.963439
8  Masculino      8 a 11 anos  3305.898320
9  Masculino          Nenhuma  3178.181818

In [21]:
# Filtrando os dados para incluir apenas nascimentos em 26/07
df_26_julho = df[df['DTNASC'].dt.strftime('%d/%m') == '26/07']
peso_medio_26_julho = df_26_julho.groupby(['SEXO', 'ESCMAE'])['PESO'].mean().reset_index()

# Exibindo os resultados
print("Peso médio dos bebês por sexo e faixa de escolaridade no dia 26 de Julho:\n", peso_medio_26_julho)

Peso médio dos bebês por sexo e faixa de escolaridade no dia 26 de Julho:
         SEXO           ESCMAE         PESO
0   Feminino       1 a 3 anos  3322.500000
1   Feminino  12 anos ou mais  3430.555556
2   Feminino       4 a 7 anos  2612.800000
3   Feminino      8 a 11 anos  3213.611111
4  Masculino       1 a 3 anos  3470.000000
5  Masculino  12 anos ou mais  3298.888889
6  Masculino       4 a 7 anos  3321.714286
7  Masculino      8 a 11 anos  2962.050000

In [90]:
peso_medio_por_sexo_escolaridade

        SEXO           ESCMAE         PESO
0   Feminino       1 a 3 anos  3126.363636
1   Feminino  12 anos ou mais  3182.427912
2   Feminino       4 a 7 anos  3158.036123
3   Feminino      8 a 11 anos  3193.247746
4   Feminino          Nenhuma  2972.333333
5  Masculino       1 a 3 anos  3191.354386
6  Masculino  12 anos ou mais  3309.658421
7  Masculino       4 a 7 anos  3288.963439
8  Masculino      8 a 11 anos  3305.898320
9  Masculino          Nenhuma  3178.181818

In [91]:
peso_medio_26_julho

        SEXO           ESCMAE         PESO
0   Feminino       1 a 3 anos  3322.500000
1   Feminino  12 anos ou mais  3430.555556
2   Feminino       4 a 7 anos  2612.800000
3   Feminino      8 a 11 anos  3213.611111
4  Masculino       1 a 3 anos  3470.000000
5  Masculino  12 anos ou mais  3298.888889
6  Masculino       4 a 7 anos  3321.714286
7  Masculino      8 a 11 anos  2962.050000

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [22]:
# Encontrando o município com o menor número de nascimentos
municipio_menos_bebes = df['munResNome'].value_counts().idxmin()

# Exibindo o resultado
print("Município com o menor número de nascimentos:", municipio_menos_bebes)

Município com o menor número de nascimentos: Município ignorado - RO

In [23]:
# Excluindo registros do "Município ignorado - RO"
df_sem_ignorado = df[df['munResNome'] != 'Município ignorado - RO']
df = df_sem_ignorado

# Encontrando o município com o menor número de nascimentos
municipio_menos_bebes = df['munResNome'].value_counts().idxmin()

# Exibindo o resultado
print("Município com o menor número de nascimentos (excluindo 'Município ignorado - RO'):", municipio_menos_bebes)

Município com o menor número de nascimentos (excluindo 'Município ignorado - RO'): Castanheiras

In [29]:
# Calculando estatísticas de idade das mães
idade_media = df[df['munResNome'] == 'Castanheiras']['IDADEMAE'].mean()
idade_maxima = df[df['munResNome'] == 'Castanheiras']['IDADEMAE'].max()
idade_minima = df[df['munResNome'] == 'Castanheiras']['IDADEMAE'].min()

# Exibindo os resultados
print(f"Idade média das mães em {'Castanheiras'}: {idade_media:.2f} anos")
print(f"Idade máxima das mães em {'Castanheiras''Castanheiras'}: {idade_maxima} anos")
print(f"Idade mínima das mães em {'Castanheiras'}: {idade_minima} anos")

Idade média das mães em Castanheiras: 27.28 anos
Idade máxima das mães em CastanheirasCastanheiras: 39 anos
Idade mínima das mães em Castanheiras: 17 anos

In [30]:
quantidade_valores_ausentes = df['IDADEPAI'].isnull().sum()
quantidade_valores_ausentes

19421

In [31]:
df.IDADEPAI.count

<bound method Series.count of 0        26.0
1        24.0
2        32.0
3        24.0
4        27.0
         ...
27023    35.0
27024     NaN
27025    30.0
27026    24.0
27027     NaN
Name: IDADEPAI, Length: 27027, dtype: float64>

In [32]:
total = 27028
nan = 19421

# Calcular a porcentagem
porcentagem = (nan / total) * 100

# Exibir o resultado
print(f"{nan} é aproximadamente {porcentagem:.2f}% de {total}.")

19421 é aproximadamente 71.86% de 27028.

*a maioria das crianças não tem pai?? Ou seria apenas uma falha na coleta de dados? Dada a maneira como os dados são coletados e os grandes volumes de dados ausentes em algumas colunas, talvez o método de coleta dos dados tenha algumas falhas.

In [33]:
# Filtrar o DataFrame para incluir apenas entradas de Castanheiras
df_castanheiras = df[df['munResNome'] == 'Castanheiras']

# Calcular a idade média, máxima e mínima dos pais
idade_media = df_castanheiras['IDADEPAI'].mean()
idade_maxima = df_castanheiras['IDADEPAI'].max()
idade_minima = df_castanheiras['IDADEPAI'].min()

# Exibir os resultados
print(f"Idade Média dos Pais em Castanheiras: {idade_media:.2f} anos")
print(f"Idade Máxima dos Pais em Castanheiras: {idade_maxima} anos")
print(f"Idade Mínima dos Pais em Castanheiras: {idade_minima} anos")

Idade Média dos Pais em Castanheiras: 30.39 anos
Idade Máxima dos Pais em Castanheiras: 43.0 anos
Idade Mínima dos Pais em Castanheiras: 17.0 anos

In [16]:
df_castanheiras = df[df['munResNome'] == 'Castanheiras']

# Preencher valores ausentes na coluna 'IDADEPAI' com a média da coluna
df_castanheiras['IDADEPAI'].fillna(df_castanheiras['IDADEPAI'].mean(), inplace=True)

# Calcular a idade média, máxima e mínima dos pais
idade_media = df_castanheiras['IDADEPAI'].mean()
idade_maxima = df_castanheiras['IDADEPAI'].max()
idade_minima = df_castanheiras['IDADEPAI'].min()

# Exibir os resultados
print(f"Idade Média dos Pais em Castanheiras: {idade_media:.2f} anos")
print(f"Idade Máxima dos Pais em Castanheiras: {idade_maxima} anos")
print(f"Idade Mínima dos Pais em Castanheiras: {idade_minima} anos")

Idade Média dos Pais em Castanheiras: 30.39 anos
Idade Máxima dos Pais em Castanheiras: 43.0 anos
Idade Mínima dos Pais em Castanheiras: 17.0 anos

C:\Users\Administrador\AppData\Local\Temp\ipykernel_10944\2933369259.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_castanheiras['IDADEPAI'].fillna(df_castanheiras['IDADEPAI'].mean(), inplace=True)

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [40]:
#Qual o municipio que nasceu mais bebe no mês de março?
df['DTNASC'] = pd.to_datetime(df['DTNASC'], errors='coerce')

# Filtrando os nascimentos que ocorreram no mês de março
nascimentos_marco = df[df['DTNASC'].dt.month == 3]

# Contando o número de nascimentos por município
nascimentos_por_municipio = nascimentos_marco['munResNome'].value_counts()

# Obtendo o município com o maior número de nascimentos em março
municipio_mais_nascimentos = nascimentos_por_municipio.idxmax()
quantidade_nascimentos = nascimentos_por_municipio.max()

# Exibindo o resultado
print(f"O município que teve mais nascimentos em março foi {municipio_mais_nascimentos}, com {quantidade_nascimentos} nascimentos.")

O município que teve mais nascimentos em março foi Porto Velho, com 744 nascimentos.

In [43]:
#qual a quantidade de filhos vivos media, maxima, minima nesse municipio?

# Filtrando o DataFrame para incluir apenas o município desejado
df_municipio = df[df['munResNome'] == 'Porto Velho']

# Calculando a quantidade média, máxima e mínima de filhos vivos
media_filhos_vivos = df_municipio['QTDFILVIVO'].mean()
max_filhos_vivos = df_municipio['QTDFILVIVO'].max()
min_filhos_vivos = df_municipio['QTDFILVIVO'].min()

# Exibindo os resultados
print(f"No município de {porto_velho}:")
print(f"Quantidade média de filhos vivos: {media_filhos_vivos:.2f}")
print(f"Quantidade máxima de filhos vivos: {max_filhos_vivos}")
print(f"Quantidade mínima de filhos vivos: {min_filhos_vivos}")

No município de Porto Velho:
Quantidade média de filhos vivos: 1.17
Quantidade máxima de filhos vivos: 12.0
Quantidade mínima de filhos vivos: 0.0

In [44]:
# Calculando a idade média, máxima e mínima dos pais
media_idade_pai = df_municipio['IDADEPAI'].mean()
max_idade_pai = df_municipio['IDADEPAI'].max()
min_idade_pai = df_municipio['IDADEPAI'].min()

# Calculando a idade média, máxima e mínima das mães
media_idade_mae = df_municipio['IDADEMAE'].mean()
max_idade_mae = df_municipio['IDADEMAE'].max()
min_idade_mae = df_municipio['IDADEMAE'].min()

# Exibindo os resultados
print(f"No município de {porto_velho} para os pais:")
print(f"Idade média dos pais: {media_idade_pai:.2f}")
print(f"Idade máxima dos pais: {max_idade_pai}")
print(f"Idade mínima dos pais: {min_idade_pai}")

print(f"\nNo município de {porto_velho} para as mães:")
print(f"Idade média das mães: {media_idade_mae:.2f}")
print(f"Idade máxima das mães: {max_idade_mae}")
print(f"Idade mínima das mães: {min_idade_mae}")

No município de Porto Velho para os pais:
Idade média dos pais: 32.35
Idade máxima dos pais: 65.0
Idade mínima dos pais: 16.0

No município de Porto Velho para as mães:
Idade média das mães: 26.31
Idade máxima das mães: 47
Idade mínima das mães: 12

Mães de 12 anos. É uma idade muito jovem para se tornar mãe.

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Em Porto Velho existem meninas que se tornam mães aos 12 anos e os meninos aos 16 anos, idades muito precoces. Imagino se outros cenários dessa cidade fossem examinados (como taxa de evasão escolar e distribuição de renda, por exemplo) forem analisados, como esses problemas podem se relacionar.

Além disso, alguns dados possuem volumes de dados ausentes muito grandes como idade do pai, última menstruação da mãe e código de anomalia cromossomica. Talvez exista alguma falha na coleta que reflita nestas perdas.